lib/keisan/ast/builder.rb
lib/keisan/calculator.rb
lib/keisan/context.rb
lib/keisan/parser.rb
lib/keisan/tokenizer.rb
lib/keisan/tokens/number.rb
lib/keisan/tokens/word.rb
spec/keisan/tokenizer_spec.rb

Does some refactoring of long methods, adds a few specs.
There was also a bug fixed that involved parsing of scientific notation numbers and variable names.  The following would register as a `Word` incorrectly before:
```ruby
Keisan::Tokenizer.new("1234e2").tokens.first.is_a?(Keisan::Tokens::Word)
#=> true
```
After it is correct
```ruby
Keisan::Tokenizer.new("1234e2").tokens.first.is_a?(Keisan::Tokens::Number)
#=> true
Keisan::Tokenizer.new("1234e2").tokens.first.value
#=> 123400.0
```

Refactor and expand specs

---

README.md
lib/keisan/tokens/number.rb
spec/keisan/tokenizer_spec.rb

Using the prefixes `0b`, `0o`, and `0x` (standard in Ruby) indicates binary, octal, and hexadecimal numbers respectively.
```ruby
calculator.evaluate("0b1100")
#=> 12
calculator.evaluate("0o775")
#=> 504
calculator.evaluate("0x1f0")
#=> 496
```

Handling binary octal hex

---

.travis.yml
keisan.gemspec
lib/keisan/tokens/group.rb

There was a difference in handling of 0-th group recursive regular expressions between Ruby 2.4 and lower version (see [here](https://stackoverflow.com/questions/43007936/discrepancy-in-scan-and-match-behavior-for-different-ruby-versions)).  This pull request fixes this problem, and opens up the lower Ruby version limit.

Handle older ruby versions

---

README.md
lib/keisan.rb
lib/keisan/ast/builder.rb
lib/keisan/ast/function.rb
lib/keisan/ast/node.rb
lib/keisan/calculator.rb
lib/keisan/context.rb
lib/keisan/evaluator.rb
lib/keisan/exceptions.rb
lib/keisan/functions/default_registry.rb
spec/keisan/calculator_spec.rb
spec/keisan/default_functions_spec.rb

Allows for string based definitions of variables and functions
```ruby
calculator.evaluate("N = 10")
calculator.evaluate("2*N")
#=> 20
calculator.evaluate("fact(n) = if (n > 1, n*fact(n-1), 1)")
calculator.evaluate("fact(5)")
#=> 120
```

Calculator can evaluate definitions

---

lib/keisan/ast/constant_literal.rb
lib/keisan/ast/exponent.rb
lib/keisan/ast/function.rb
lib/keisan/ast/number.rb
lib/keisan/ast/plus.rb
lib/keisan/ast/string.rb
lib/keisan/ast/times.rb
lib/keisan/ast/unary_inverse.rb
lib/keisan/ast/unary_minus.rb
lib/keisan/ast/unary_operator.rb
lib/keisan/ast/unary_plus.rb
lib/keisan/ast/variable.rb
lib/keisan/exceptions.rb
spec/keisan/ast/node_spec.rb

Some basic simplifications for special handling of 0 and 1.
- Products with a 0 factor become 0
- Products have 1 terms dropped
- Sums have 0 terms dropped
- `a**b` for b = 1 are reduced to `a`
- Fractions with 1 in denominator are reduced to just the numerator

More symbolic

---

lib/keisan/ast.rb
lib/keisan/ast/assignment.rb
lib/keisan/ast/function.rb
lib/keisan/ast/node.rb
lib/keisan/ast/parent.rb
lib/keisan/ast/plus.rb
lib/keisan/ast/unary_operator.rb
lib/keisan/ast/variable.rb
lib/keisan/context.rb
lib/keisan/evaluator.rb
lib/keisan/function_definition_context.rb
lib/keisan/functions/default_registry.rb
lib/keisan/functions/expression_function.rb
lib/keisan/functions/if.rb
lib/keisan/functions/proc_function.rb
lib/keisan/functions/registry.rb
lib/keisan/variables/registry.rb
spec/keisan/ast/assignment_spec.rb
spec/keisan/calculator_spec.rb
spec/keisan/context_spec.rb
spec/keisan/default_functions_spec.rb
spec/keisan/default_variables_spec.rb
spec/keisan/functions/proc_function_spec.rb
spec/keisan/functions/registry_spec.rb
spec/keisan/variables/registry_spec.rb

With these changes, function definitions are now stored internally correctly using the expressions AST as opposed to lambdas/procs.  This will allow lazy evaluation for operations like differentiation to work with user defined functions.

Expression functions

---

README.md
lib/keisan/ast/exponent.rb
lib/keisan/ast/function.rb
lib/keisan/function.rb
lib/keisan/functions/expression_function.rb
spec/keisan/ast/node_spec.rb
spec/readme_spec.rb

Issue #25 
Implements chain rule for user defined functions.  This is possible because the use of `ExpressionFunction` means that user defined functions remember their exact definition, so it is possible to calculate derivatives based on this.  This is what it looks like in use:
```ruby
calculator = Keisan::Calculator.new
calculator.evaluate("f(x, y) = x**2 + y")
calculator.evaluate("replace(diff(f(2*t, t+1), t), t, 3)")
#=> 25
```

Expression function derivative

---

README.md
lib/keisan/calculator.rb
lib/keisan/evaluator.rb
spec/keisan/calculator_spec.rb
spec/readme_spec.rb

`Keisan::Calculator#evaluate` requires all variables/functions to be defined.  However, the user might still want to see the simplified version of an expression even with undefined elements present.  This PR adds the `Keisan::Calculator#simplify` method to accomplish this.
```ruby
calculator.evaluate("1*(0*2+x*g(t))")
#=> Keisan::Exceptions::UndefinedVariableError: x
calculator.simplify("1*(0*2+x*g(t))")
#=> "x*g(t)"
```
This can be used to just see what the result of a differentiation operator is too
```ruby
calculator.simplify("diff(sin(2*x), x)")
#=> "2*cos(2*x)"
```
This also adds another useful helper method: `ast` which simply parses an expression and returns the AST to the user.  This is for a user who might want to do their own manipulations to the syntax tree.

Calculator simplify method

---

lib/keisan/ast/assignment.rb
lib/keisan/ast/function.rb
lib/keisan/ast/indexing.rb
lib/keisan/ast/multi_line.rb
lib/keisan/ast/node.rb
lib/keisan/ast/operator.rb
lib/keisan/functions/expression_function.rb
spec/keisan/ast/assignment_spec.rb
spec/keisan/calculator_spec.rb

This change evaluates only assignments of the RHS of assignments.  We want to leave the RHS of a function definition alone.

`evaluate` should not evaluate RHS of assignment

---

README.md
lib/keisan/ast/assignment.rb
lib/keisan/context.rb
lib/keisan/functions/default_registry.rb
lib/keisan/functions/let.rb
lib/keisan/parser.rb
lib/keisan/parsing/function.rb
lib/keisan/tokenizer.rb
spec/keisan/ast/builder_spec.rb
spec/keisan/ast/node_spec.rb
spec/keisan/context_spec.rb
spec/keisan/let_spec.rb
spec/keisan/parser_spec.rb
spec/keisan/tokenizer_spec.rb
spec/readme_spec.rb

Currently variables are all essentially globally defined.  This PR adds the `let` keyword that makes it so assignment to a variable/function will not bubble up to the parent context.  The difference between using `let` or not can be seen in the following:
```
keisan> x = 1; {x = 2}; x
=> 2
keisan> x = 1; {let x = 2}; x
=> 1
```
In the first case, inside the brace changing `x` changes it in the upper scope, but in the second case using `let` forces the assignment to only be local to the block.

`let` keyword

---

lib/keisan.rb
lib/keisan/ast/constant_literal.rb
lib/keisan/ast/literal.rb
lib/keisan/ast/variable.rb
spec/keisan_spec.rb

`Keisan` module now contains an internal `Calculator` that can be readily accessed for quick console testing.
```
Keisan["1 + 2"]
#=> 3
```

Add useful module methods for Keisan

---

lib/keisan/context.rb
lib/keisan/functions/registry.rb
lib/keisan/variables/registry.rb
spec/keisan/context_spec.rb
spec/keisan/default_functions_spec.rb
spec/keisan/default_variables_spec.rb

With these changes, it is now possible to define variables/functions even if they collide with a parent context.  If the parent context's variable/function can be modified, such definitions will be modified, otherwise a new variable will be locally defined that shadows the parent one.  Variable/function definitions can be frozen by calling `freeze` on the context.

Allow local definitions to shadow defaults

---

lib/keisan/interpreter.rb

Currently `bin/keisan` will freeze up when given no options and no piped input, when it should really open the REPL in that case.  This fixes the problem by detecting when there is piped input or not.

Fix interpreter to work without piped input

---

lib/keisan.rb
lib/keisan/parser.rb
lib/keisan/tokenizer.rb
lib/keisan/tokens/unknown.rb
spec/keisan/ast/builder_spec.rb
spec/keisan/calculator_spec.rb

In regular mathematics, "2x" is 2 times "x".  Along these lines, this pull request tries to re-interpret simple concatenation of elements as multiplication.  There are some caveats with this:
- `2x` == `2*x`, but `xy` will be interpreted as the variable `xy` still (although `x y` == `x*y`)
- `5(1+2)` == `5*(1+2)`, but `f(1+2)` will still be interpreted as a function call (can overcome this by using brackets like `(f)(1+2)` which becomes `f*(1+2)`)

Space is multiplication

---

keisan.gemspec
lib/keisan.rb
lib/keisan/ast/builder.rb
lib/keisan/ast/operator.rb
lib/keisan/ast/parent.rb
lib/keisan/ast/unary_operator.rb
lib/keisan/context.rb
lib/keisan/parser.rb
lib/keisan/parsing/function.rb
lib/keisan/parsing/hash.rb
lib/keisan/token.rb
lib/keisan/util.rb

Issue #66 
Removes the `activesupport` dependency.

Remove activesupport dependency

---

lib/keisan/context.rb
spec/keisan/let_spec.rb

Previously using a child context derived from `context.spawn_child` would not define local variables when using `let`.  This was because the `local` variable was not being passed on as an argument to successive calls to `register_variable!`.  This fixes this problem.

`let` makes variables local to current context

---

lib/keisan/ast/boolean.rb
lib/keisan/ast/cell.rb
lib/keisan/ast/logical_and.rb
lib/keisan/ast/logical_equal.rb
lib/keisan/ast/logical_greater_than.rb
lib/keisan/ast/logical_greater_than_or_equal_to.rb
lib/keisan/ast/logical_less_than_or_equal_to.rb
lib/keisan/ast/logical_not_equal.rb
lib/keisan/ast/logical_operator.rb
lib/keisan/ast/logical_or.rb
spec/keisan/ast/logical_spec.rb
spec/keisan/functions/while_spec.rb

Previously trying to implement an `includes` method that would loop through an array and return true if the given element is found would not work.  This PR fixes that, does some refactoring of logical operators, and ensures that `&&` and `||` operators short-circuit as appropriate.

Logical refactoring and handle short-circuiting

---

README.md
lib/keisan/ast/function.rb
lib/keisan/ast/logical_less_than.rb
lib/keisan/function.rb
lib/keisan/functions/enumerable_function.rb
lib/keisan/functions/filter.rb
lib/keisan/functions/map.rb
lib/keisan/functions/reduce.rb
lib/keisan/variables/default_registry.rb
spec/keisan/ast/function_assignment_spec.rb
spec/readme_spec.rb

Previously a function assignment like `"double(a) = a.map(x, 2*x)"` would fail without curly braces because `x` was undefined.  However the `x` argument to `map` is _supposed_ to be an unbound variable, so this PR updates the code to handle correctly this problem and make such an assignment possible.  See the spec changes for examples of such now allowable assignments.

Unbound variables works with enumerable functions

---

lib/keisan/ast/node.rb
lib/keisan/ast/unary_inverse.rb
lib/keisan/ast/variable.rb
lib/keisan/functions/cmath_function.rb
lib/keisan/functions/expression_function.rb
lib/keisan/functions/proc_function.rb
lib/keisan/functions/replace.rb
spec/keisan/calculator_spec.rb
spec/keisan/differentiation_spec.rb

Previously it was not possible to calculate the derivatives of a user defined function, like `"f(x) = x*log(x); diff(f(x), x)"`, even though one could calculate the derivative directly, `"diff(x*log(x), x)"`.  This pull request remedies this problem.

Differentiation should work with user defined functions

---

.travis.yml
keisan.gemspec
lib/keisan.rb
lib/keisan/string_and_group_parser.rb
lib/keisan/tokenizer.rb
lib/keisan/tokens/group.rb
lib/keisan/tokens/string.rb
spec/keisan/calculator_spec.rb
spec/keisan/string_and_group_parser_spec.rb
spec/keisan/tokenizer_spec.rb
spec/spec_helper.rb

Previously unmatched braces inside strings would cause tokenization
errors. The expected behavior is that braces inside of strings would not
participate in brace matching (as they are part of a string). This
commit handles strings/brace-groups separately, making sure to match
opening/closing braces/quotations correctly.
This fixes issue #94.

Fix brace matching problem inside strings

---

README.md
lib/keisan/functions/default_registry.rb
spec/keisan/ast/date_spec.rb
spec/keisan/ast/time_spec.rb
spec/readme_spec.rb

Adds two new functions: `epoch_days` and `epoch_seconds`.  These compute the number of days/seconds respectively since Unix epoch, 00:00:00 on Jan 1st, 1970.  They can be used for instance to write a function which computes the number of days between two dates:
```
diff_days(a, b) = a.epoch_days - b.epoch_days
diff_days(date(2020, 4, 4), date(2020, 4, 1))
#=> 3
```

Methods to get days/seconds since Unix epoch

---

lib/keisan/ast/block.rb
lib/keisan/ast/cell.rb
lib/keisan/ast/function_assignment.rb
lib/keisan/ast/hash.rb
lib/keisan/ast/node.rb
lib/keisan/ast/parent.rb
lib/keisan/calculator.rb
lib/keisan/context.rb
lib/keisan/evaluator.rb
spec/keisan/ast/node_spec.rb
spec/keisan/calculator_spec.rb

These new options can be used to further lock-down the expressions that are permitted by the calculator class.

New flags to disallow blocks/multiline expressions

---

lib/keisan/string_and_group_parser.rb
lib/keisan/tokenizer.rb
spec/keisan/calculator_spec.rb
spec/keisan/string_and_group_parser_spec.rb
spec/keisan/tokenizer_spec.rb

Resolves #101
Previously, due to inconsistent handling of stripping out comments in combination with strings, hashtags `#` caused problems.  This PR fixes the problem by ensuring that when a hashtag character is encountered outside of a string, all characters up to the end of the string or the next new-line character are considered comments and stripped out.

Handle comments separately from strings

---

lib/keisan/version.rb
spec/keisan_spec.rb
spec/version_spec.rb

Incorporates changes from #102 which fixes how comments are stripped out when strings are encountered with the `#` character.

Update version to 0.8.4

---

lib/keisan/string_and_group_parser.rb
lib/keisan/tokenizer.rb
spec/keisan/calculator_spec.rb
spec/keisan/parser_spec.rb
spec/keisan/string_and_group_parser_spec.rb
spec/keisan/tokenizer_spec.rb

Fixes #105 
There was a problem with the way escaped characters was handled that this PR fixes. Previously the distinction between the raw underlying string and the escaped version of a string was not made clear.
When parsing something like `("\"a")`, our parser would identify this as a StringAndGroupParser::GroupPortion (the outer round brackets) with an interior StringPortion correctly. However, the interior StringPortion will have converted the escaped double-quote into a double-quote character, and so the `to_s` method would return the string `""a"`. Due to the way GroupPortion is handled in Keisan::Tokenizer, the part inside the parenthesis is recursively passed into another Tokenizer object using the content of the StringPortion as input. However, the `to_s` method of the …

Fix handling of escaped characters within brackets

---

lib/keisan/functions/enumerable_function.rb
spec/keisan/default_functions_spec.rb

Hi @shioyama, @project-eutopia,
The purpose of this PR is to allow enumerable functions (`map`, `filter` etc..) on hash values.
E.g.
```ruby
calc = Keisan::Calculator.new
calc.evaluate("my_hash['ary'].map(x, x['a']*2)", my_hash: { 'ary' => [{ 'a' => 2 }, { 'a' => 3 }] })
```
With the current version of keisan the above would throw a `Keisan::Exceptions::InvalidFunctionError (Unhandled first argument to filter: [{ 'a' => 2 }, { 'a' => 3 }])` because the value is not recognised as being a `List` or `Hash` (it's a `Cell`). The PR fixes that.
Let me know if you have any preference on the specs, code style or the way to handle this issue. Happy to update my PR based on your guidance.

Allow enumerable functions on hash values / AST::Cell

---

lib/keisan/context.rb
lib/keisan/version.rb
spec/keisan/context_spec.rb
spec/version_spec.rb

Creates a new method `set_random` to `Context`. This allows one to override the Random instance used by a Context object. The `random` method has also been updated to not constantly make a new Random object if called multiple times when `@random` is not set.

Add set random method to context

---

lib/keisan/calculator.rb
lib/keisan/context.rb
spec/keisan/default_functions_spec.rb

If this flag is set to false, then evaluation of random methods,
`rand` and `sample`, will raise an error.

allow_random toggles validity of random methods

---

lib/keisan/ast/block.rb
lib/keisan/ast/cell.rb
lib/keisan/ast/hash.rb
lib/keisan/ast/node.rb
lib/keisan/ast/parent.rb
lib/keisan/version.rb
spec/keisan/ast/node_spec.rb
spec/version_spec.rb

This method takes in a block, which is evaluated on each node in the AST
in depth-first order. If the block returns a truthy value for any of the
nodes, then the search stops and this value is returned.

Traverse method

---

README.md
lib/keisan/ast/assignment.rb
lib/keisan/ast/list_assignment.rb
lib/keisan/variables/registry.rb
lib/keisan/version.rb
spec/keisan/ast/assignment_spec.rb
spec/readme_spec.rb
spec/version_spec.rb

New feature: multiple assignments can now be performed in a single line. To do this, you wrap the assignments in a list on both sides. For instance, to assign to two variables:
```
[x, y] = [3, 5]
```
This works in the following manner:
- The RHS is evaluated
- If the RHS is not a list or of different length than the LHS, then an error is raise
- Finally the individual assignments are performed from left to right (e.g. "[a, b, c] = [1, 2, 3]" first does "a = 1", then "b = 2", then "c = 3")
- This has all the same features of normal assignment, e.g. compound operators like `+=` can be used, or assignment to individual list / hash elements can be done.

Multiple assignment

---

lib/keisan/ast/constant_literal.rb
lib/keisan/ast/function.rb
lib/keisan/ast/hash.rb
lib/keisan/ast/node.rb
lib/keisan/ast/parent.rb
lib/keisan/functions/enumerable_function.rb
lib/keisan/version.rb
spec/keisan/ast/boolean_spec.rb
spec/keisan/ast/date_spec.rb
spec/keisan/ast/function_spec.rb
spec/keisan/ast/hash_spec.rb
spec/keisan/ast/list_spec.rb
spec/keisan/ast/null_spec.rb
spec/keisan/ast/number_spec.rb
spec/keisan/ast/string_spec.rb
spec/keisan/ast/time_spec.rb
spec/keisan/calculator_spec.rb
spec/version_spec.rb

Previously, an expression like "5 == nil" would not immediately evaluate to true. This PR makes it so that equality comparisons between constants can be done between different types consistently. If the two operands are constants, then they are by default not equal unless the `equal` or `not_equal` method is overridden (e.g. AST::Number has an override which can properly compare Number to Number, but a Number != String for instance).
The complex function defined in `calculator_spec.rb` demonstrates a case where this expression non-evaluation would raise problems.

Fix handling of constants in expressions

---

lib/keisan/ast/cell.rb
lib/keisan/ast/logical_and.rb
lib/keisan/ast/logical_or.rb
lib/keisan/functions/filter.rb
lib/keisan/functions/if.rb
lib/keisan/functions/while.rb
lib/keisan/version.rb
spec/keisan/ast/cell_spec.rb
spec/keisan/ast/logical_spec.rb
spec/keisan/default_functions_spec.rb
spec/keisan/functions/filter_spec.rb
spec/keisan/functions/if_spec.rb
spec/keisan/functions/while_spec.rb
spec/version_spec.rb

Previously, innocuous statements like `"if(x[0], x[1], x[2])"` could cause problems because of the way list/hash values are unwrapped. This problem exists wherever boolean statements are used, e.g. if statements, while loops, and filters.
This PR fixes the issue by unwrapping `Keisan::AST::Cell` objects for the purpose of checking the boolean value wherever possible. It also now will raise errors if these logical functions receive non-boolean constants as arguments (e.g. `"if(x[0], ...)"` when `x[0]` evaluates to say a string `"foo"`).

Fix boolean checks when embedded in a cell

---

lib/keisan/ast/unary_logical_not.rb
spec/keisan/ast/logical_spec.rb
spec/keisan/functions/filter_spec.rb
spec/keisan/functions/if_spec.rb
spec/keisan/functions/while_spec.rb

Boolean expressions for functions like if/while/filter would previously
have problems with unary logical not. This fixes the problem.
See also #118 for other similar work on logical and/or.

Fix handling of unary logical nots

---

lib/keisan/ast/operator.rb
lib/keisan/ast/plus.rb
lib/keisan/ast/times.rb

Having `@parsing_operators` stored on some AST nodes is not needed. It takes up extra memory and clutters the objects.

Do not store @parsing_operators on AST

---

README.md
lib/keisan.rb
lib/keisan/ast/cache.rb
lib/keisan/calculator.rb
lib/keisan/evaluator.rb
spec/keisan/ast/cache_spec.rb
spec/readme_spec.rb

Creates new class `Keisan::AST::Cache` to support caching computation of ASTs from strings. See the changes to the README for more details on this feature.

Caching ASTs

---

lib/keisan/calculator.rb
lib/keisan/evaluator.rb
spec/keisan/calculator_spec.rb

Creates methods `evaluate_ast` and `simplify_ast`, which are equivalent to `evaluate` and `simplify`, but work on ASTs instead of expressions. This allows one to for instance first compute the AST of an expression, do some checks on it, and then evaluating it without having to re-parse the expression.

Method to evaluate/simplify an AST

---

lib/keisan/parser.rb
lib/keisan/parsing/hash.rb
spec/keisan/calculator_spec.rb
spec/keisan/parser_spec.rb

Previously a simple expression like `"h = {}"` would set `h` to `nil`. This is because the curly braces would be recognized as a *block* instead of a *hash*. This PR updates the code to treat curly braces that have no internal content as a blank hash.

Empty curly-braces is treated as a blank hash

---

lib/keisan/functions/enumerable_function.rb
spec/keisan/default_functions_spec.rb

Currently trying to chain a function defined using a Proc with a function like `map` causes an error. This PR fixes this by calling `evaluate` on the lhs instead of `simplify` (which doesn't know how to simplify a Proc function).

Can chain Proc functions with `map` and other enumerable functions

---

lib/keisan/parsing/hash.rb
spec/keisan/ast/hash_spec.rb
spec/keisan/ast/list_spec.rb

Previously, lists could be defined across multiple lines, but hashes could not. This PR makes this more consistent by also stripping out newlines from inside the curly-braces defining a hash.

Allow hash to be defined across multiple lines

---

lib/keisan/ast/indexing.rb
spec/keisan/ast/indexing_spec.rb

Previously the methods `#deep_dup` and `#freeze` were not defined for `Indexing` AST objects, which means they only duplicate and freeze the arguments and not the indexes in an expression like `arg[index]`. This PR fixes this problem.

Indexing can deep_dup and freeze indexes too

---

lib/keisan/functions/expression_function.rb
lib/keisan/functions/registry.rb
spec/keisan/functions/registry_spec.rb

Do not want expressions that are saved in a function to ever change, so we freeze them.

Ensure ExpressionFunctions are frozen

---

README.md
lib/keisan/functions/default_registry.rb
spec/keisan/ast/cache_spec.rb
spec/keisan/calculator_spec.rb
spec/keisan/default_functions_spec.rb
spec/readme_spec.rb

Resolves #129.
Adds four new methods: `difference`, `intersection`, `union`, and `uniq`. These are defined to behave just like in Ruby. So one caveat is that `difference` will return the same element multiple times if it occurs multiple times in the LHS (see test included in this PR). Otherwise, these first 3 behave just like their set theoretical counterparts, and if you ensure that each list has no duplicates using `uniq` then the functions should behave exactly like the set ones.

Add set methods for lists

---

lib/keisan/ast/assignment.rb
lib/keisan/ast/multi_line.rb
spec/keisan/ast/assignment_spec.rb
spec/keisan/ast/multi_line_spec.rb
spec/keisan/differentiation_spec.rb

Following up on #132, this updates the logic for `unbound_variables` to better handle multi-line statements. In particular, assignment like "x = 3" will now report no unbound variables, and multi-line statements like "x = 1; y = x" will also realize there are no unbound variables.

Correct unbound variable handly in multi-line
