lib/keisan/ast/function.rb, lib/keisan/ast/node.rb, lib/keisan/ast/variable.rb, lib/keisan/context.rb, lib/keisan/functions/registry.rb, lib/keisan/variables/registry.rb, spec/keisan/ast/node_spec.rb, spec/keisan/context_spec.rb
The methods `unbound_variables` and `unbound_functions` return a set of all undefined variables and functions respectively for a given AST.
=> Get unbound variables functions

lib/keisan/ast/constant_literal.rb, lib/keisan/ast/indexing.rb, lib/keisan/evaluator.rb, spec/keisan/ast/node_spec.rb
Indexing for lists can be simplified by `simplified` too.
=> Simplification works with lists and indexings

.travis.yml, README.md, spec/readme_spec.rb
To ensure the code examples in the README remain up-to-date, we parse the code examples and run them in specs.  Inspired by Rust documentation tests: https://doc.rust-lang.org/beta/rustdoc/documentation-tests.html
=> Readme spec

lib/keisan/ast/variable.rb, lib/keisan/evaluator.rb, lib/keisan/functions/cos.rb, lib/keisan/functions/cot.rb, lib/keisan/functions/csc.rb, lib/keisan/functions/default_registry.rb, lib/keisan/functions/exp.rb, lib/keisan/functions/expression_function.rb, lib/keisan/functions/if.rb, lib/keisan/functions/log.rb, lib/keisan/functions/math_function.rb, lib/keisan/functions/sec.rb, lib/keisan/functions/sin.rb, lib/keisan/functions/tan.rb, spec/keisan/ast/node_spec.rb, spec/keisan/default_variables_spec.rb, spec/keisan/functions/if_spec.rb
Issue #23 
Implementation of derivatives for basic trigonometric functions, exp, and log.
=> Math function derivatives

lib/keisan/functions/expression_function.rb, spec/keisan/ast/node_spec.rb
Do not want to substitute in variable values when calculating partial derivatives.
=> Fix partial derivatives calculation

README.md, lib/keisan/ast/list.rb, lib/keisan/context.rb, lib/keisan/functions/default_registry.rb, lib/keisan/functions/filter.rb, lib/keisan/functions/map.rb, lib/keisan/functions/registry.rb, lib/keisan/variables/registry.rb, spec/keisan/default_functions_spec.rb, spec/readme_spec.rb
Issue: #27 
Adds initial functional programming support for `map` and `filter` methods.
=> Functional programming

lib/keisan/calculator.rb, lib/keisan/context.rb, lib/keisan/repl.rb
`allow_recursive` command in REPL
=> Recursion in REPL

README.md, lib/keisan/functions/default_registry.rb, lib/keisan/functions/filter.rb, lib/keisan/functions/map.rb, lib/keisan/functions/reduce.rb, spec/keisan/default_functions_spec.rb, spec/readme_spec.rb
Completes the functional programming trifecta of `map`, `filter`, `reduce`.
=> Add `reduce` function programming method

README.md, lib/keisan/functions/default_registry.rb, lib/keisan/functions/filter.rb, lib/keisan/functions/map.rb, lib/keisan/functions/reduce.rb, spec/keisan/default_functions_spec.rb, spec/readme_spec.rb
Issue #27
Adds the `reverse`, `flatten`, and `range` methods.
=> More array methods

lib/keisan/function.rb, lib/keisan/functions/diff.rb, lib/keisan/functions/expression_function.rb, lib/keisan/functions/filter.rb, lib/keisan/functions/map.rb, lib/keisan/functions/proc_function.rb, lib/keisan/functions/rand.rb, lib/keisan/functions/reduce.rb, lib/keisan/functions/sample.rb
Function argument size validation refactoring.
=> Refactor arity

lib/keisan/ast/node.rb, lib/keisan/functions/default_registry.rb, lib/keisan/functions/while.rb, spec/keisan/functions/while_spec.rb
Adds a first attempt at implementing the `while` loop.
=> Initial `while` function

lib/keisan/functions/default_registry.rb, lib/keisan/functions/erf.rb, spec/keisan/default_functions_spec.rb
Adds the factorial function, and combinatorical choose and permute functions.  Also adds derivative for the error function `erf`.
=> Add combinatorical methods

README.md, lib/keisan.rb, lib/keisan/ast/assignment.rb, lib/keisan/ast/cell.rb, lib/keisan/ast/indexing.rb, lib/keisan/ast/list.rb, lib/keisan/ast/variable.rb, lib/keisan/variables/registry.rb, spec/keisan/ast/cell_spec.rb, spec/keisan/ast/indexing_spec.rb, spec/keisan/ast/list_spec.rb, spec/keisan/calculator_spec.rb, spec/readme_spec.rb
Currently can access elements of a list using square brackets, but cannot change the values stored within a variable list.  This PR adds a `Cell` type, which is essentially a reference wrapper to a node, which allows updating the values stored within variables.
=> Assignment to lists

README.md, keisan.gemspec, lib/keisan/ast/node.rb, lib/keisan/ast/unary_identity.rb, lib/keisan/functions/if.rb, lib/keisan/parser.rb, lib/keisan/variables/default_registry.rb, spec/keisan/ast/node_spec.rb, spec/keisan/ast/unary_identity_spec.rb, spec/keisan/calculator_spec.rb, spec/keisan/parser_spec.rb, spec/readme_spec.rb, spec/spec_helper.rb
Adds coverage checks, improves some coverage, and adds a coverage badge to the README.
=> Add simplecov

README.md, lib/keisan/ast/multi_line.rb, lib/keisan/functions/default_registry.rb, lib/keisan/functions/expression_function.rb, lib/keisan/functions/if.rb, lib/keisan/functions/let.rb, lib/keisan/functions/rand.rb, lib/keisan/functions/range.rb, lib/keisan/parser.rb, spec/keisan/ast/assignment_spec.rb, spec/keisan/functions/if_spec.rb, spec/keisan/let_spec.rb, spec/readme_spec.rb, spec/spec_helper.rb
See also: #45 
Various refactorings, minor bug fixes, and increasing of coverage with more specs.
=> Improve code: Take 2

README.md, lib/keisan/functions/default_registry.rb, lib/keisan/functions/puts.rb, lib/keisan/parser.rb, spec/keisan/puts_spec.rb, spec/readme_spec.rb
Users can now write results of expressions to STDOUT.
=> Support for `puts` in expressions

lib/keisan/functions/sample.rb, spec/keisan/default_functions_spec.rb
Just like in Ruby, `sample([1,2,3,4], 2)` will return an array of 2 randomly sampled elements.
=> `sample` function 2nd argument number of elements

lib/keisan/ast/hash.rb, lib/keisan/ast/list.rb, lib/keisan/functions/default_registry.rb, lib/keisan/functions/to_h.rb, spec/keisan/ast/hash_spec.rb, spec/keisan/default_functions_spec.rb
Ruby-like `to_h` method that can convert lists of key,value pairs into a hash.
=> `to_h` method

lib/keisan/ast/boolean.rb, lib/keisan/ast/null.rb, lib/keisan/ast/string.rb, lib/keisan/functions/enumerable_function.rb, lib/keisan/functions/filter.rb, lib/keisan/functions/map.rb, lib/keisan/functions/reduce.rb, spec/keisan/ast/boolean_spec.rb, spec/keisan/ast/null_spec.rb, spec/keisan/ast/string_spec.rb, spec/keisan/default_functions_spec.rb
Adds support for using the functional programming methods `map`, `select`, and `inject` on hashes as well.
=> Functional programming for hashes

lib/keisan/ast/date.rb, lib/keisan/ast/date_time_methods.rb, lib/keisan/ast/time.rb
Refactors out some common methods for dates and times.
=> Refactor date and time

README.md, spec/readme_spec.rb
Adds info about date and time methods (#83 and #84) to the README file.
=> Add date and time info to README

README.md, spec/readme_spec.rb
Updates README.md to mention comments. This was an oversight I noticed thanks to #101 and #102.
=> Update documentation to explain comments

lib/keisan/version.rb, spec/version_spec.rb
Includes fix to #105 provided by #106.
=> Update to version 0.8.5

lib/keisan/ast/number.rb, lib/keisan/version.rb, spec/keisan/calculator_spec.rb, spec/version_spec.rb
Currently it is possible to evaluate something like "1/1" to a Rational number, even though it is nicer to simplify this to the Integer it really is. This PR makes this simplification.
=> If Rational denominator 1, convert to Integer
